# Deploy + AUTOSCALING
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment-service
  namespace: default
  labels:
    app: gateway-container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-container
  template:
    metadata:
      labels:
        app: gateway-container
    spec:
      containers:
        - name: gateway-container-container
          image: me-west1-docker.pkg.dev/ceevee-ai-v1/my-repo/gateway-container:v1 #docker.io/ao5000cookiesh/ao-art:v1 #me-west1-docker.pkg.dev/superb-system-382911/my-repo/ao-art:v1
          ports:
            - containerPort: 8080
      tolerations:
        - key: instance_type
          value: spot
          effect: NoSchedule
          operator: Equal
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: team
                    operator: In
                    values:
                      - me-team
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - gateway-container
              topologyKey: kubernetes.io/hostname
